name: Deploy
run-name: "@${{ github.actor }} was pushed up a new update. Auto-Redeploy START!"
on: 
  workflow_dispatch: 
  # push:
  #   branches:
  #   - 'main'
  #   - 'develop/**'
  
jobs:     
  # Docker-Image-Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Create .env file
  #       run: |
  #         echo "${{ secrets.ENV_PRODUCTION_FILE }}" > .env.production
  #         ls -a
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: zyxma/plannet:latest

  SSH-Remote-Deploy:
    # needs: Docker-Image-Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          git clone https://${{ GITHUB_TOKEN }}@github.com/6MA-606/PROJECT2-SEC-2-Point-of-Vue plannet
          cd ./plannet
          git fetch
          git pull
          docker compose up -d --build
